version: '3.8'

services:
  vbi_fe:
    build:
      context: ..
      dockerfile: docker/vbi_fe/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - vbi_be
    restart: unless-stopped
    networks:
      - vbi_net

  vbi_be:
    build:
      context: ..
      dockerfile: docker/vbi_be/Dockerfile
    ports:
      - '3030:3030'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=123456
      - DB_DATABASE=vbi
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - vbi_net

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vbi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - vbi_net

volumes:
  postgres_data:

networks:
  vbi_net:
