name: Bug Server CI

# 这里业务方根据需求设置
on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/vseed/**'
  push:
    branches: ['main']
    paths:
      - 'packages/vseed/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 10.13.1

      - name: Install Dependencies
        run: pnpm install

      - name: Print All Github Environment Variables
        run: env

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm --filter '!website' build

      - name: Run CI
        working-directory: ./tools/bugserver-trigger
        env:
          BUG_SERVER_TOKEN: ${{ secrets.BUG_SERVER_TOKEN }}
        run: pnpm run ci
