name: Bug Server CI

# 这里业务方根据需求设置
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'develop', 'dev/*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Print All Github Environment Variables
        run: env

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run:  pnpm run build --filter @internal/bugserver-trigger

      - name: Run CI
        working-directory: ./tools/bugserver-trigger
        env:
          BUG_SERVER_TOKEN: ${{ secrets.BUG_SERVER_TOKEN }}
        run: pnpm run ci
